name: "Manual Trigger Workflow"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: ./
        with:
          apiKey: ${{ secrets.MARATHON_CLOUD_API_TOKEN }}
          application: "example/app.apk"
          testApplication: "example/appTest.apk"
          platform: android
          name: "3_0"
          output: "output"
          outputGlob: "tests/**"
          version: "1.0.15"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
