name: "Manual Trigger Workflow"

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: ./
        with:
          apiKey: ${{ secrets.MARATHON_CLOUD_API_TOKEN }}
          application: "example/app.apk"
          testApplication: "example/appTest.apk"
          platform: android
          name: "android_3_0"
          output: "output"
          outputGlob: "tests/**"
          version: "1.0.15"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output

  build_ios:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests parallel
        uses: ./
        with:
          apiKey: ${{ secrets.MARATHON_CLOUD_API_TOKEN }}
          application: "example/sample.zip"
          testApplication: "example/sampleUITests-Runner.zip"
          platform: ios
          name: "ios_3_0"
          output: "output2"
          outputGlob: "tests/**"
          version: "1.0.15"

      - name: Upload artifact parallel
        uses: actions/upload-artifact@v2
        with:
          name: output2
          path: output2
